In [1]:
import pandas as pd
from joblib import  load

In [2]:
data_path = '../Data'
model_path = '../Models'

In [9]:
X = pd.read_csv('{}/accidents_merge.zip'.format(data_path))

c:\temp\eric.favre\temp\ipykernel_23132\3603298639.py:1: DtypeWarning: Columns (20,26,27,56) have mixed types. Specify dtype option on import or set low_memory=False.
  X = pd.read_csv('{}/accidents_merge.zip'.format(data_path))


In [16]:
X['lat']= X['lat'].str.replace(',','.').astype('float')
X['long']= X['long'].str.replace(',','.').astype('float')

In [17]:
import folium

In [18]:
map = folium.Map(location=[0,0], zoom_start=1)

In [ ]:
for lat, long in X[['lat','long']].iterrows() :
    print(lat, long)

0 lat     48.89621
long     2.47012
Name: 0, dtype: float64
1 lat     48.89621
long     2.47012
Name: 1, dtype: float64
2 lat     48.89621
long     2.47012
Name: 2, dtype: float64
3 lat     48.9307
long     2.3688
Name: 3, dtype: float64
4 lat     48.935872
long     2.319174
Name: 4, dtype: float64
5 lat     48.935872
long     2.319174
Name: 5, dtype: float64
6 lat     48.935872
long     2.319174
Name: 6, dtype: float64
7 lat     48.935872
long     2.319174
Name: 7, dtype: float64
8 lat     48.817329
long     2.428150
Name: 8, dtype: float64
9 lat     48.817329
long     2.428150
Name: 9, dtype: float64
10 lat     48.817329
long     2.428150
Name: 10, dtype: float64
11 lat     48.817329
long     2.428150
Name: 11, dtype: float64
12 lat     48.776362
long     2.433254
Name: 12, dtype: float64
13 lat     48.776362
long     2.433254
Name: 13, dtype: float64
14 lat     48.776362
long     2.433254
Name: 14, dtype: float64
15 lat     45.84694
long     1.23386
Name: 15, dtype: float64
16 lat  

In [5]:
import tensorflow as tf
model = tf.keras.models.load_model('./..//neural_network/results/2class_neural_network_model.h5')

d:\Streamlit\.venv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
d:\Streamlit\.venv\Lib\site-packages\keras\src\optimizers\base_optimizer.py:86: UserWarning: Argument `decay` is no longer supported and will be ignored.
  warnings.warn(


In [5]:
X = pd.read_csv('test.csv')

In [6]:
X = X.drop('Unnamed: 0', axis = 1)

In [11]:
X

mois_1  mois_2  mois_3  mois_4  mois_5  mois_6  mois_7  mois_8  mois_9  \
0       1       0       0       0       0       0       0       0       0   

   mois_10  ...  secu_1  secu_2  secu_3  secu_4  secu_5  secu_6  secu_7  \
0        0  ...       0       0       0       0       0       0       0   

   secu_8  secu_9  weekend  
0       0       0        0  

[1 rows x 337 columns]

In [8]:
x = [X.values.flatten().tolist()]

prediction = model.predict(x)
#predicted_class = np.argmax(prediction, axis=1)

ValueError: Unrecognized data type: x=[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0894161373474176, -0.5020608556820431, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]] (of type <class 'list'>)

In [3]:
X_test = pd.read_csv('{}/X_test.zip'.format(data_path))

In [19]:
X_test

mois_1  mois_2  mois_3  mois_4  mois_5  mois_6  mois_7  mois_8  mois_9  \
0         0.0     0.0     0.0     0.0     0.0     0.0     0.0     1.0     0.0   
1         0.0     0.0     0.0     0.0     0.0     0.0     0.0     1.0     0.0   
2         1.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3         0.0     0.0     0.0     0.0     0.0     1.0     0.0     0.0     0.0   
4         0.0     0.0     0.0     0.0     0.0     0.0     0.0     1.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
88219     0.0     0.0     0.0     0.0     0.0     0.0     0.0     1.0     0.0   
88220     0.0     0.0     0.0     0.0     0.0     0.0     1.0     0.0     0.0   
88221     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
88222     0.0     0.0     0.0     0.0     1.0     0.0     0.0     0.0     0.0   
88223     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       mois_10  ...  secu_1  secu_2  secu_3  secu_4  secu_5  secu_6  secu_7  \
0          0.0  ...     0.0     1.0     0.0     0.0     0.0     0.0     0.0   
1          0.0  ...     1.0     0.0     0.0     0.0     0.0     0.0     0.0   
2          0.0  ...     1.0     0.0     0.0     0.0     0.0     0.0     0.0   
3          0.0  ...     0.0     1.0     0.0     0.0     0.0     1.0     0.0   
4          0.0  ...     1.0     0.0     0.0     0.0     0.0     0.0     0.0   
...        ...  ...     ...     ...     ...     ...     ...     ...     ...   
88219      0.0  ...     0.0     1.0     0.0     0.0     0.0     0.0     0.0   
88220      0.0  ...     0.0     1.0     0.0     0.0     0.0     1.0     0.0   
88221      1.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
88222      0.0  ...     0.0     1.0     0.0     0.0     0.0     0.0     0.0   
88223      1.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       secu_8  secu_9  weekend  
0         0.0     0.0      0.0  
1         0.0     0.0      0.0  
2         0.0     0.0      0.0  
3         0.0     0.0      0.0  
4         0.0     0.0      1.0  
...       ...     ...      ...  
88219     0.0     0.0      0.0  
88220     0.0     0.0      0.0  
88221     0.0     0.0      0.0  
88222     0.0     0.0      0.0  
88223     0.0     0.0      0.0  

[88224 rows x 337 columns]

In [20]:
X

mois_1  mois_2  mois_3  mois_4  mois_5  mois_6  mois_7  mois_8  mois_9  \
0       1       0       0       0       0       0       0       0       0   

   mois_10  ...  secu_1  secu_2  secu_3  secu_4  secu_5  secu_6  secu_7  \
0        0  ...       0       0       0       0       0       0       0   

   secu_8  secu_9  weekend  
0       0       0        0  

[1 rows x 337 columns]

In [12]:
X

Num_Acc_x  jour  mois    an   hrmn  lum dep    com  agg  int  ...  \
0       201900000001    30    11  2019  01:30    4  93  93053    1    1  ...   
1       201900000001    30    11  2019  01:30    4  93  93053    1    1  ...   
2       201900000001    30    11  2019  01:30    4  93  93053    1    1  ...   
3       201900000002    30    11  2019  02:50    3  93  93066    1    1  ...   
4       201900000003    28    11  2019  15:15    1  92  92036    1    1  ...   
...              ...   ...   ...   ...    ...  ...  ..    ...  ...  ...  ...   
494177  202200055301     1     1  2022  08:40    1  81  81099    1    3  ...   
494178  202200055301     1     1  2022  08:40    1  81  81099    1    3  ...   
494179  202200055301     1     1  2022  08:40    1  81  81099    1    3  ...   
494180  202200055302     1     3  2022  16:55    1  41  41018    2    1  ...   
494181  202200055302     1     3  2022  16:55    1  41  41018    2    1  ...   

        sexe  an_nais trajet secu1 secu2  secu3 locp  actp etatp  id_usager  
0          2   2002.0      0     1     0     -1   -1    -1    -1        NaN  
1          2   1993.0      5     1     0     -1   -1    -1    -1        NaN  
2          1   1959.0      0     1     0     -1   -1    -1    -1        NaN  
3          2   1994.0      0     1     0     -1   -1    -1    -1        NaN  
4          1   1996.0      0     1     0     -1   -1     0    -1        NaN  
...      ...      ...    ...   ...   ...    ...  ...   ...   ...        ...  
494177     2   2002.0      5     1    -1     -1    0     0    -1    968 230  
494178     2   2004.0      5     1    -1     -1    0     0    -1    968 231  
494179     2   1953.0      5     1    -1     -1    0     0    -1    968 232  
494180     1   1992.0      1     2     6     -1   -1    -1    -1    968 228  
494181     1   2000.0     -1     1    -1     -1   -1    -1    -1    968 229  

[494182 rows x 57 columns]

In [13]:
X['lat','long']

KeyError: ('lat', 'long')

In [20]:
pred = model.predict(X_test)

2757/2757 ━━━━━━━━━━━━━━━━━━━━ 20s 7ms/step


In [10]:
from tensorflow.keras.optimizers import Adam
model.compile(optimizer=Adam(learning_rate=0.0005),
              loss='categorical_crossentropy',  # Perte pour multi-classes
              metrics=['accuracy', 
                       tf.keras.metrics.Precision(name="precision"),
                       tf.keras.metrics.Recall(name="recall"),
                       tf.keras.metrics.AUC(name="auc")])

In [12]:
pred.shape

(11, 1)

In [31]:
model = tf.keras.models.load_model('./..//neural_network/results/2class_neural_network_model.h5')
X_test = pd.read_csv('{}/X_test.zip'.format(data_path))
XX_test = X_test.loc[:10]
pred = model.predict(X)
pred

d:\Streamlit\.venv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
d:\Streamlit\.venv\Lib\site-packages\keras\src\optimizers\base_optimizer.py:86: UserWarning: Argument `decay` is no longer supported and will be ignored.
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 297ms/step


array([[0.02421972, 0.06611556, 0.8462061 , 0.06345857]], dtype=float32)

In [17]:
pd.DataFrame(data = pred)

0
0     1.139220e-07
1     1.545813e-06
2     3.019770e-08
3     2.268915e-07
4     3.494303e-07
...            ...
996   2.463283e-07
997   4.780312e-09
998   1.563914e-06
999   5.515147e-08
1000  3.111180e-08

[1001 rows x 1 columns]

In [21]:
sum(pred > 0.6)

array([0])

In [16]:
1 pred 

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False]])

In [19]:
import numpy as np
np.hstack((1-pred, pred))

array([[9.9999988e-01, 1.1392198e-07],
       [9.9999845e-01, 1.5458129e-06],
       [9.9999994e-01, 3.0197697e-08],
       [9.9999976e-01, 2.2689147e-07],
       [9.9999964e-01, 3.4943031e-07],
       [9.9999619e-01, 3.8314615e-06],
       [9.9999982e-01, 1.9515909e-07],
       [9.9999994e-01, 7.5067888e-08],
       [9.9999994e-01, 6.4622029e-08],
       [9.9999988e-01, 1.3927296e-07],
       [9.9999928e-01, 7.0634309e-07]], dtype=float32)

In [26]:
X

mois  lum  agg  int  atm  col  catr  circ  nbv  vosp  ...  secu_4  \
0         11    4    1    1    1    2     1     3   10     0  ...       0   
1         11    4    1    1    1    2     1     3   10     0  ...       0   
2         11    4    1    1    1    2     1     3   10     0  ...       0   
3         11    3    1    1    1    6     1     1    2     0  ...       0   
4         11    1    1    1    1    4     1     3    8     0  ...       0   
...      ...  ...  ...  ...  ...  ...   ...   ...  ...   ...  ...     ...   
442984     1    3    1    1    9    6     3     2    2     0  ...       0   
442985     1    1    1    3    1    3     3     2    2     0  ...       0   
442986     1    1    1    3    1    3     3     2    2     0  ...       0   
442987     1    1    1    3    1    3     3     2    2     0  ...       0   
442988     3    1    2    1    1    2     3     3    4     0  ...       0   

        secu_5  secu_6  secu_7  secu_8  secu_9  hh  weekend  classe_age  \
0            0       0       0       0       0   1        1           1   
1            0       0       0       0       0   1        1           3   
2            0       0       0       0       0   1        1           4   
3            0       0       0       0       0   2        1           3   
4            0       0       0       0       0  15        0           2   
...        ...     ...     ...     ...     ...  ..      ...         ...   
442984       0       0       0       0       0   4        1           3   
442985       0       0       0       0       0   8        1           2   
442986       0       0       0       0       0   8        1           2   
442987       0       0       0       0       0   8        1           5   
442988       0       1       0       0       0  16        0           3   

        geoloc  
0           54  
1           54  
2           54  
3           54  
4            4  
...        ...  
442984      46  
442985      39  
442986      39  
442987      39  
442988      16  

[442989 rows x 40 columns]

In [45]:
X.loc[X['geoloc']== 1 && X['grav']==3,]

SyntaxError: invalid syntax (2020983918.py, line 1)

In [58]:
len(X.query('grav == 3 and geoloc == 40'))

170

In [57]:
len(X.query('geoloc == 40'))

4364

In [56]:
405/66957*100


0.6048658094000627

In [67]:
df = X.groupby(['geoloc','grav']).size() *100 / X.groupby(['geoloc']).size()

In [ ]:
df = pd.DataFrame(df)

In [77]:
df = df.reset_index()

In [80]:
df[df['grav'] == 3][0].max()

14.018691588785046

In [6]:
kmeans = load('{}/../Models/clustering_geoloc.joblib'.format(model_path))

d:\Streamlit\.venv\Lib\site-packages\sklearn\base.py:380: InconsistentVersionWarning: Trying to unpickle estimator KMeans from version 1.5.2 when using version 1.6.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(


In [89]:
len(kmeans.labels_)

442989

In [94]:
labels = kmeans.labels_

In [98]:
labels.count(40)

AttributeError: 'numpy.ndarray' object has no attribute 'count'

In [104]:
u, c = np.unique(labels, return_counts= True)

In [7]:
pd.DataFrame.from_dict(data = {'0': [48.516604348867475, 2.3291015625000004]}, orient = 'index', columns = ['lat','long'])

lat      long
0  48.516604  2.329102

In [8]:
kmeans.predict(pd.DataFrame.from_dict(data = {'0': [5.74261022090537, 4.833984375000001]}, orient = 'index', columns = ['lat','long']))

array([73])